// <auto-generated />
using Koszyk.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Koszyk.Migrations
{
    [DbContext(typeof(KoszykContext))]
    [Migration("20181025090817_urlzdjecia")]
    partial class urlzdjecia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Koszyk.Models.Produkt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adresProducenta")
                        .IsRequired();

                    b.Property<decimal>("cenaNetto");

                    b.Property<int>("ilosc");

                    b.Property<string>("nazwa")
                        .IsRequired();

                    b.Property<string>("nazwaProducenta")
                        .IsRequired();

                    b.Property<string>("urlZdjecia");

                    b.HasKey("id");

                    b.ToTable("produkty");
                });
#pragma warning restore 612, 618
        }
    }
}
